version: '3.7'

networks:
  proxy:
    name: proxy-network

services:
  database:
    build:
      context: ./database
      dockerfile: Dockerfile.dev
    image: certsys/database
    container_name: certsys_test_database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=developer
      - POSTGRES_PASSWORD=dv1010aa
      - POSTGRES_DB=certsys_test
    volumes:
      - postgres-database:/data/postgres
    networks:
      - proxy

  server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: certsys_test_server
    depends_on:
      - database
    ports:
      - 4000:4000
    environment:
      - DB_HOST=certsys_test_database
      - DB_SYNC=true
    volumes:
      - .:/usr/app
    networks:
      - proxy

volumes:
  postgres-database:
    driver: local